### ISSUE TITLE
Many of your SQL statements are susceptible to SQL Injections

### ISSUE THREAD

**Issue by vbatecan** [Abhi143210/Employe_Management#2]
Your code is at risk of SQL injection. It means that attackers can manipulate your database by injecting malicious code into the inputs. You should implement proper safeguards like parameterized queries or prepared statements to prevent this vulnerability.
o protect your code from SQL injection, use parameterized queries, sanitize user inputs, avoid direct embedding of input into queries, follow least privilege principles, keep your database system updated, and stay informed about security best practices.

**Comment by Abhi143210** [comment]
Thank You For your Kind Information I did this Project for learning purposes only and also I will correct and update Prepared statement soon.  and Thank You
